# Generated by Django 5.0.6 on 2024-06-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0002_alter_talla_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='id_talla',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='id_tipo_bici',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='rut',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
        migrations.DeleteModel(
            name='TipoBici',
        ),
        migrations.DeleteModel(
            name='Arriendo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
