# Generated by Django 5.0.6 on 2024-06-24 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterBikes', '0003_remove_arriendo_id_talla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(db_column='idFormaPago', primary_key=True, serialize=False)),
                ('forma', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(db_column='idTalla', primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBici',
            fields=[
                ('id_tipo_bici', models.AutoField(db_column='idTipoBici', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.AutoField(db_column='idArriendo', primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=80)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('id_forma_pago', models.ForeignKey(db_column='idFormaPago', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.formapago')),
                ('id_talla', models.ForeignKey(db_column='idTalla', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.talla')),
                ('id_tipo_bici', models.ForeignKey(db_column='idTipoBici', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.tipobici')),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.usuario')),
            ],
        ),
    ]
