# Generated by Django 5.0.6 on 2024-06-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0007_pago_detalle_despacho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapago',
            options={'verbose_name_plural': 'Formas de pago'},
        ),
        migrations.AlterModelOptions(
            name='reparacion',
            options={'verbose_name_plural': 'Reparaciones'},
        ),
    ]
