# Generated by Django 5.0.6 on 2024-06-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='rut',
        ),
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
