# Generated by Django 5.0.6 on 2024-06-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0012_pago_detalle_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='problema',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
