# Generated by Django 5.0.6 on 2024-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0014_alter_despacho_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='recibo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
