# Generated by Django 5.0.6 on 2024-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0015_alter_despacho_envio_alter_despacho_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(db_column='Tipo de Usuario', max_length=30),
        ),
    ]
