# Generated by Django 5.0.6 on 2024-06-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0016_alter_tipousuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='id_forma_pago',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='id_talla',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='id_tipo_bici',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_forma_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_tipo_producto',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
        migrations.DeleteModel(
            name='TipoBici',
        ),
        migrations.DeleteModel(
            name='Arriendo',
        ),
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='FormaPago',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
        migrations.DeleteModel(
            name='Reparacion',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
