# Generated by Django 5.0.6 on 2024-07-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBikes', '0018_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(db_column='idItem', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('id_carrito', models.ForeignKey(db_column='idCarrito', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.carrito')),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='MasterBikes.producto')),
            ],
        ),
    ]
